// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr0g-vdKyeFuXTZ7pGoa5_CYhsvVbFYXY',
    appId: '1:111744966421:web:3ae4d685facc463339931c',
    messagingSenderId: '111744966421',
    projectId: 'fittrack-1807',
    authDomain: 'fittrack-1807.firebaseapp.com',
    storageBucket: 'fittrack-1807.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY4FWC4-bq6m-X6gEUyzKZgsQ1yxe2xuY',
    appId: '1:111744966421:android:3a83f2db40e6b5b139931c',
    messagingSenderId: '111744966421',
    projectId: 'fittrack-1807',
    storageBucket: 'fittrack-1807.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ_yRSphEGRCi8XWHnE7apnaPlBLybSxM',
    appId: '1:111744966421:ios:aeee611f826a6e1039931c',
    messagingSenderId: '111744966421',
    projectId: 'fittrack-1807',
    storageBucket: 'fittrack-1807.firebasestorage.app',
    iosBundleId: 'com.example.fittrackApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ_yRSphEGRCi8XWHnE7apnaPlBLybSxM',
    appId: '1:111744966421:ios:aeee611f826a6e1039931c',
    messagingSenderId: '111744966421',
    projectId: 'fittrack-1807',
    storageBucket: 'fittrack-1807.firebasestorage.app',
    iosBundleId: 'com.example.fittrackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr0g-vdKyeFuXTZ7pGoa5_CYhsvVbFYXY',
    appId: '1:111744966421:web:6c41f07159cef90d39931c',
    messagingSenderId: '111744966421',
    projectId: 'fittrack-1807',
    authDomain: 'fittrack-1807.firebaseapp.com',
    storageBucket: 'fittrack-1807.firebasestorage.app',
  );
}
